roles:
- name: filled
  components: [Button, FileLoader]
- name: outlined
  components: [Button, FileLoader]
  display_in_toolbox: false
- name: input-error
  components: [TextBox, TextArea, DatePicker]
- name: card
  components: [ColumnPanel]
  display_in_toolbox: true
  title: Card
- name: display
  components: [Label, Link]
- name: headline
  components: [Label, Link]
- name: title
  components: [Label, Link]
- name: body
  components: [Label, Link]
- name: input-prompt
  components: [Label, Link]
color_scheme:
  preset_groups:
  - name: Colour Scheme
    options:
    - name: Material Light
      colors:
      - {name: Primary, color: '#6750A4'}
      - {name: Primary Container, color: '#EADDFF'}
      - {name: On Primary, color: '#FFFFFF'}
      - {name: On Primary Container, color: '#21005E'}
      - {name: Secondary, color: '#625B71'}
      - {name: Secondary Container, color: '#E8DEF8'}
      - {name: On Secondary, color: '#FFFFFF'}
      - {name: On Secondary Container, color: '#1E192B'}
      - {name: Tertiary, color: '#7D5260'}
      - {name: Tertiary Container, color: '#FFD8E4'}
      - {name: On Tertiary, color: '#FFFFFF'}
      - {name: On Tertiary Container, color: '#370B1E'}
      - {name: Error, color: '#B3261E'}
      - {name: Background, color: '#FFFBFE'}
      - {name: Surface, color: '#FFFBFE'}
      - {name: On Background, color: '#1C1B1F'}
      - {name: On Surface, color: '#1C1B1F'}
      - {name: Surface Variant, color: '#E7E0EC'}
      - {name: On Surface Variant, color: '#49454E'}
      - {name: Outline, color: '#79747E'}
      - {name: On Disabled, color: 'rgba(28, 27, 31, 0.38)'}
      - {name: Disabled Container, color: 'rgba(28, 27, 31, 0.12)'}
      - {name: Light Overlay 1, color: 'rgba(255, 255, 255, 0.08)'}
      - {name: Light Overlay 2, color: 'rgba(255, 255, 255, 0.12)'}
      - {name: Dark Overlay 1, color: 'rgba(30, 25, 43, 0.08)'}
      - {name: Dark Overlay 2, color: 'rgba(30, 25, 43, 0.12)'}
      - {name: Primary Overlay 1, color: 'rgba(103, 80, 164, 0.05)'}
      - {name: Primary Overlay 2, color: 'rgba(103, 80, 164, 0.08)'}
      - {name: Primary Overlay 3, color: 'rgba(103, 80, 164, 0.11)'}
    - name: Material Dark
      colors:
      - {name: Primary, color: '#D0BCFF'}
      - {name: Primary Container, color: '#4F378B'}
      - {name: On Primary, color: '#371E73'}
      - {name: On Primary Container, color: '#EADDFF'}
      - {name: Secondary, color: '#CCC2DC'}
      - {name: Secondary Container, color: '#4A4458'}
      - {name: On Secondary, color: '#332D41'}
      - {name: On Secondary Container, color: '#E8DEF8'}
      - {name: Tertiary, color: '#EFB8C8'}
      - {name: Tertiary Container, color: '#633B48'}
      - {name: On Tertiary, color: '#492532'}
      - {name: On Tertiary Container, color: '#FFD8E4'}
      - {name: Error, color: '#F2B8B5'}
      - {name: Background, color: '#1C1B1F'}
      - {name: Surface, color: '#1C1B1F'}
      - {name: On Background, color: '#E6E1E5'}
      - {name: On Surface, color: '#E6E1E5'}
      - {name: Surface Variant, color: '#49454F'}
      - {name: On Surface Variant, color: '#CAC4D0'}
      - {name: Outline, color: '#938F99'}
      - {name: On Disabled, color: 'rgba(230, 225, 229, 0.38)'}
      - {name: Disabled Container, color: 'rgba(230, 225, 229, 0.12)'}
      - {name: Light Overlay 1, color: 'rgba(232, 222, 248, 0.08)'}
      - {name: Light Overlay 2, color: 'rgba(232, 222, 248, 0.12)'}
      - {name: Dark Overlay 1, color: 'rgba(232, 222, 248, 0.08)'}
      - {name: Dark Overlay 2, color: 'rgba(232, 222, 248, 0.12)'}
      - {name: Primary Overlay 1, color: 'rgba(208, 188, 255, 0.05)'}
      - {name: Primary Overlay 2, color: 'rgba(208, 188, 255, 0.08)'}
      - {name: Primary Overlay 3, color: 'rgba(208, 188, 255, 0.11)'}
    - name: Paradise Light
      colors:
      - {name: Primary, color: '#006C51'}
      - {name: Primary Container, color: '#82F8CE'}
      - {name: On Primary, color: '#FFFFFF'}
      - {name: On Primary Container, color: '#002116'}
      - {name: Secondary, color: '#4C6359'}
      - {name: Secondary Container, color: '#CEE8DB'}
      - {name: On Secondary, color: '#FFFFFF'}
      - {name: On Secondary Container, color: '#082018'}
      - {name: Tertiary, color: '#3F6375'}
      - {name: Tertiary Container, color: '#C3E8FD'}
      - {name: On Tertiary, color: '#FFFFFF'}
      - {name: On Tertiary Container, color: '#001E2B'}
      - {name: Error, color: '#BA1B1B'}
      - {name: Background, color: '#F1FFF7'}
      - {name: Surface, color: '#F1FFF7'}
      - {name: On Background, color: '#191C1B'}
      - {name: On Surface, color: '#191C1B'}
      - {name: Surface Variant, color: '#DBE5DF'}
      - {name: On Surface Variant, color: '#3F4944'}
      - {name: Outline, color: '#707974'}
      - {name: On Disabled, color: 'rgba(25, 28, 27, 0.38)'}
      - {name: Disabled Container, color: 'rgba(25, 28, 27, 0.12)'}
      - {name: Light Overlay 1, color: 'rgba(0, 108, 81, 0.08)'}
      - {name: Light Overlay 2, color: 'rgba(0, 108, 81, 0.12)'}
      - {name: Dark Overlay 1, color: 'rgba(8, 32, 24, 0.08)'}
      - {name: Dark Overlay 2, color: 'rgba(8, 32, 24, 0.12)'}
      - {name: Primary Overlay 1, color: 'rgba(0, 108, 81, 0.05)'}
      - {name: Primary Overlay 2, color: 'rgba(0, 108, 81, 0.08)'}
      - {name: Primary Overlay 3, color: 'rgba(0, 108, 81, 0.11)'}
    - name: Paradise Dark
      colors:
      - {name: Primary, color: '#64DBB4'}
      - {name: Primary Container, color: '#00513C'}
      - {name: On Primary, color: '#003829'}
      - {name: On Primary Container, color: '#002116'}
      - {name: Secondary, color: '#B2CCC0'}
      - {name: Secondary Container, color: '#344B42'}
      - {name: On Secondary, color: '#1E352C'}
      - {name: On Secondary Container, color: '#CEE9DC'}
      - {name: Tertiary, color: '#A7CCE1'}
      - {name: Tertiary Container, color: '#264B5D'}
      - {name: On Tertiary, color: '#0B3445'}
      - {name: On Tertiary Container, color: '#C3E8FE'}
      - {name: Error, color: '#FFB4A9'}
      - {name: Background, color: '#191C1B'}
      - {name: Surface, color: '#191C1B'}
      - {name: On Background, color: '#E1E3E0'}
      - {name: On Surface, color: '#E1E3E0'}
      - {name: Surface Variant, color: '#3F4944'}
      - {name: On Surface Variant, color: '#BFC9C3'}
      - {name: Outline, color: '#8A938E'}
      - {name: On Disabled, color: 'rgba(225, 227, 224, 0.38)'}
      - {name: Disabled Container, color: 'rgba(225, 227, 224, 0.12)'}
      - {name: Light Overlay 1, color: 'rgba(206, 233, 220, 0.08)'}
      - {name: Light Overlay 2, color: 'rgba(206, 233, 220, 0.12)'}
      - {name: Dark Overlay 1, color: 'rgba(206, 233, 220, 0.08)'}
      - {name: Dark Overlay 2, color: 'rgba(206, 233, 220, 0.12)'}
      - {name: Primary Overlay 1, color: 'rgba(100, 219, 180, 0.05)'}
      - {name: Primary Overlay 2, color: 'rgba(100, 219, 180, 0.08)'}
      - {name: Primary Overlay 3, color: 'rgba(100, 219, 180, 0.11)'}
    - name: Rally Dark
      colors:
      - {name: Primary, color: '#1EB980'}
      - {name: Primary Container, color: '#005235'}
      - {name: On Primary, color: '#003824'}
      - {name: On Primary Container, color: '#73FBBC'}
      - {name: Secondary, color: '#B4CCBC'}
      - {name: Secondary Container, color: '#364B3F'}
      - {name: On Secondary, color: '#20352A'}
      - {name: On Secondary Container, color: '#D0E8D8'}
      - {name: Tertiary, color: '#A4CDDD'}
      - {name: Tertiary Container, color: '#234C5A'}
      - {name: On Tertiary, color: '#063542'}
      - {name: On Tertiary Container, color: '#C0E9FA'}
      - {name: Error, color: '#D64D47'}
      - {name: Background, color: '#191C1A'}
      - {name: Surface, color: '#191C1A'}
      - {name: On Background, color: '#E1E3DF'}
      - {name: On Surface, color: '#E1E3DF'}
      - {name: Surface Variant, color: '#404943'}
      - {name: On Surface Variant, color: '#C0C9C1'}
      - {name: Outline, color: '#8A938C'}
      - {name: Dark Overlay 1, color: 'rgba(208, 232, 216, 0.2)'}
      - {name: Dark Overlay 2, color: 'rgba(208, 232, 216, 0.5)'}
      - {name: Light Overlay 1, color: 'rgba(208, 232, 216, 0.2)'}
      - {name: Light Overlay 2, color: 'rgba(208, 232, 216, 0.5)'}
      - {name: Disabled Container, color: 'rgba(133, 133, 139, 0.12)'}
      - {name: On Disabled, color: '#85858B'}
      - {name: Primary Overlay 1, color: 'rgba(30, 185, 128, 0.05)'}
      - {name: Primary Overlay 2, color: 'rgba(30, 185, 128, 0.08)'}
      - {name: Primary Overlay 3, color: 'rgba(30, 185, 128, 0.11)'}
    - name: Rally Light
      colors:
      - {name: Primary, color: '#006C48'}
      - {name: Primary Container, color: '#00A36C'}
      - {name: On Primary, color: '#FFFFFF'}
      - {name: On Primary Container, color: '#002113'}
      - {name: Secondary, color: '#496455'}
      - {name: Secondary Container, color: '#CBEAD6'}
      - {name: On Secondary, color: '#FFFFFF'}
      - {name: On Secondary Container, color: '#052014'}
      - {name: Tertiary, color: '#326576'}
      - {name: Tertiary Container, color: '#B8EAFF'}
      - {name: On Tertiary, color: '#FFFFFF'}
      - {name: On Tertiary Container, color: '#001F28'}
      - {name: Error, color: '#D64D47'}
      - {name: Background, color: '#FBFDF8'}
      - {name: Surface, color: '#FBFDF8'}
      - {name: On Background, color: '#191C1A'}
      - {name: On Surface, color: '#191C1A'}
      - {name: Surface Variant, color: '#DCE5DD'}
      - {name: On Surface Variant, color: '#404943'}
      - {name: Outline, color: '#707973'}
      - {name: Dark Overlay 1, color: 'rgba(5, 32, 20, 0.8)'}
      - {name: Dark Overlay 2, color: 'rgba(51, 51, 61, 0.12)'}
      - {name: Light Overlay 1, color: 'rgba(255, 255, 255, 0.8)'}
      - {name: Light Overlay 2, color: 'rgba(255, 255, 255, 0.12)'}
      - {name: Disabled Container, color: 'rgba(25, 28, 26, 0.12)'}
      - {name: On Disabled, color: 'rgba(25, 28, 26, 0.38)'}
      - {name: Primary Overlay 1, color: 'rgba(0, 108, 72, 0.05)'}
      - {name: Primary Overlay 2, color: 'rgba(0, 108, 72, 0.08)'}
      - {name: Primary Overlay 3, color: 'rgba(0, 108, 72, 0.11)'}
    - name: Mykonos
      colors:
      - {name: Primary, color: '#00658D'}
      - {name: Primary Container, color: '#C3E7FF'}
      - {name: On Primary, color: '#FFFFFF'}
      - {name: On Primary Container, color: '#001E2D'}
      - {name: Secondary, color: '#4F616E'}
      - {name: Secondary Container, color: '#D1E5F4'}
      - {name: On Secondary, color: '#FFFFFF'}
      - {name: On Secondary Container, color: '#0A1E28'}
      - {name: Tertiary, color: '#61597C'}
      - {name: Tertiary Container, color: '#FFD8E4'}
      - {name: On Tertiary, color: '#FFFFFF'}
      - {name: On Tertiary Container, color: '#E8DDFF'}
      - {name: Error, color: '#BA1B1B'}
      - {name: Background, color: '#FBFCFF'}
      - {name: Surface, color: '#FBFCFF'}
      - {name: On Background, color: '#191C1E'}
      - {name: On Surface, color: '#191C1E'}
      - {name: Surface Variant, color: '#DDE3EA'}
      - {name: On Surface Variant, color: '#41484D'}
      - {name: Outline, color: '#71787E'}
      - {name: On Disabled, color: 'rgba(25, 28, 30, 0.38)'}
      - {name: Disabled Container, color: 'rgba(25, 28, 30, 0.12)'}
      - {name: Light Overlay 1, color: 'rgba(255, 255, 255, 0.08)'}
      - {name: Light Overlay 2, color: 'rgba(255, 255, 255, 0.12)'}
      - {name: Dark Overlay 1, color: 'rgba(10, 30, 40, 0.08)'}
      - {name: Dark Overlay 2, color: 'rgba(10, 30, 40, 0.12)'}
      - {name: Primary Overlay 1, color: 'rgba(0, 101, 141, 0.05)'}
      - {name: Primary Overlay 2, color: 'rgba(0, 101, 141, 0.08)'}
      - {name: Primary Overlay 3, color: 'rgba(0, 101, 141, 0.11)'}
  colors:
  - {name: Primary, color: '#1EB980'}
  - {name: Primary Container, color: '#005235'}
  - {name: On Primary, color: '#003824'}
  - {name: On Primary Container, color: '#73FBBC'}
  - {name: Secondary, color: '#B4CCBC'}
  - {name: Secondary Container, color: '#364B3F'}
  - {name: On Secondary, color: '#20352A'}
  - {name: On Secondary Container, color: '#D0E8D8'}
  - {name: Tertiary, color: '#A4CDDD'}
  - {name: Tertiary Container, color: '#234C5A'}
  - {name: On Tertiary, color: '#063542'}
  - {name: On Tertiary Container, color: '#C0E9FA'}
  - {name: Error, color: '#D64D47'}
  - {name: Background, color: '#191C1A'}
  - {name: Surface, color: '#191C1A'}
  - {name: On Background, color: '#E1E3DF'}
  - {name: On Surface, color: '#E1E3DF'}
  - {name: Surface Variant, color: '#404943'}
  - {name: On Surface Variant, color: '#C0C9C1'}
  - {name: Outline, color: '#8A938C'}
  - {name: Dark Overlay 1, color: 'rgba(208, 232, 216, 0.2)'}
  - {name: Dark Overlay 2, color: 'rgba(208, 232, 216, 0.5)'}
  - {name: Light Overlay 1, color: 'rgba(208, 232, 216, 0.2)'}
  - {name: Light Overlay 2, color: 'rgba(208, 232, 216, 0.5)'}
  - {name: Disabled Container, color: 'rgba(133, 133, 139, 0.12)'}
  - {name: On Disabled, color: '#85858B'}
  - {name: Primary Overlay 1, color: 'rgba(30, 185, 128, 0.05)'}
  - {name: Primary Overlay 2, color: 'rgba(30, 185, 128, 0.08)'}
  - {name: Primary Overlay 3, color: 'rgba(30, 185, 128, 0.11)'}
